name: Docker workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - name: Teste build via serviços
        run: echo ${{ job.services.postgres.ports['5432'] }}
