name: Docker workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
    runs-on: ubuntu-latest
    steps:
      - name: Teste build via serviços
        run: |
          ls -lt pgdata
          echo OK
