name: Docker workflow
on:
  push:
    branches: [ main ]
permissions: read-all|write-all
jobs:
  build:
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: hackme
        ports:
          - 5432:5432
        volumes:
          - /pgdata:/var/lib/postgresql/data
    runs-on: ubuntu-latest
    steps:
      - name: Teste build via serviços
        run: |
          ls -lt /pgdata | exit 1
          echo OK
